/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventarios;

/**
 *
 * @author Ignacio Hernandez
 */
public class IngresosArticulos extends javax.swing.JFrame {

    /**
     * Creates new form IngresosArticulos
     */
    public IngresosArticulos() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        equipo = new javax.swing.JComboBox();
        resolucion = new javax.swing.JLabel();
        ram = new javax.swing.JLabel();
        dd = new javax.swing.JLabel();
        pulgadas = new javax.swing.JLabel();
        lector = new javax.swing.JLabel();
        ip = new javax.swing.JLabel();
        impresora = new javax.swing.JLabel();
        marca = new javax.swing.JLabel();
        modeloddd = new javax.swing.JLabel();
        serie = new javax.swing.JLabel();
        cajaresolucion = new javax.swing.JTextField();
        cajaram = new javax.swing.JTextField();
        cajadd = new javax.swing.JTextField();
        cajapulgadas = new javax.swing.JTextField();
        combolector = new javax.swing.JComboBox();
        cajaip = new javax.swing.JTextField();
        cajaimpresora = new javax.swing.JTextField();
        cajamarca = new javax.swing.JTextField();
        cajamodelo = new javax.swing.JTextField();
        cajaserie = new javax.swing.JTextField();
        explicaion = new javax.swing.JTextField();
        combohdmi = new javax.swing.JComboBox();
        combousb = new javax.swing.JComboBox();
        hdmi = new javax.swing.JLabel();
        usb = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        jLabel4.setText("Tipo de Equipo* :");

        equipo.setBackground(new java.awt.Color(0, 102, 255));
        equipo.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        equipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Impresora", "PC", "Laptop", "EQ.Video Conferencia", "Scanner", "Proyector" }));
        equipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        equipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipoActionPerformed(evt);
            }
        });

        resolucion.setFont(new java.awt.Font("Leelawadee", 1, 12)); // NOI18N
        resolucion.setText("Resolucion :");

        ram.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        ram.setText("Tamaño de RAM : ");

        dd.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        dd.setText("Tamaño de Disco Duro :");

        pulgadas.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        pulgadas.setText("Pulgadas : ");

        lector.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        lector.setText("Cuenta Con Lector DVD :");

        ip.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        ip.setText("Direccion ip :");

        impresora.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        impresora.setText("Tipo de Impresora:");

        marca.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        marca.setText("Marca*  :");

        modeloddd.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        modeloddd.setText("Modelo* :");

        serie.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        serie.setText("No.Serie* :");

        cajaresolucion.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajaresolucion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaresolucion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaresolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaresolucionActionPerformed(evt);
            }
        });

        cajaram.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajaram.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaram.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaramActionPerformed(evt);
            }
        });

        cajadd.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajadd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajadd.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaddActionPerformed(evt);
            }
        });

        cajapulgadas.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        cajapulgadas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajapulgadas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajapulgadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajapulgadasActionPerformed(evt);
            }
        });

        combolector.setBackground(new java.awt.Color(0, 102, 255));
        combolector.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        combolector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "SI", "NO" }));
        combolector.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        combolector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combolector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combolectorActionPerformed(evt);
            }
        });

        cajaip.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cajaip.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaip.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaipActionPerformed(evt);
            }
        });

        cajaimpresora.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cajaimpresora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaimpresora.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaimpresora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaimpresoraActionPerformed(evt);
            }
        });

        cajamarca.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cajamarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajamarca.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajamarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajamarcaActionPerformed(evt);
            }
        });

        cajamodelo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cajamodelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajamodelo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajamodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajamodeloActionPerformed(evt);
            }
        });

        cajaserie.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        cajaserie.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cajaserie.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cajaserie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaserieActionPerformed(evt);
            }
        });

        explicaion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        explicaion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        explicaion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        explicaion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explicaionActionPerformed(evt);
            }
        });

        combohdmi.setBackground(new java.awt.Color(0, 102, 255));
        combohdmi.setFont(new java.awt.Font("Gulim", 1, 10)); // NOI18N
        combohdmi.setForeground(new java.awt.Color(255, 255, 255));
        combohdmi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "SI", "NO" }));
        combohdmi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        combohdmi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combohdmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combohdmiActionPerformed(evt);
            }
        });

        combousb.setBackground(new java.awt.Color(0, 102, 255));
        combousb.setFont(new java.awt.Font("Gulim", 1, 10)); // NOI18N
        combousb.setForeground(new java.awt.Color(255, 255, 255));
        combousb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "SI", "NO" }));
        combousb.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        combousb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combousb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combousbActionPerformed(evt);
            }
        });

        hdmi.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        hdmi.setText("Puerto HMDI :");

        usb.setFont(new java.awt.Font("Gulim", 1, 12)); // NOI18N
        usb.setText("Puertos USB :");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Agregar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addGap(68, 68, 68)
                        .addComponent(equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(ram)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cajaram, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(resolucion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cajaresolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(dd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cajadd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lector)
                            .addComponent(pulgadas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cajapulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combolector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(explicaion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(serie)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cajaserie, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(modeloddd)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cajamodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(marca)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cajamarca, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(impresora)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cajaimpresora, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(ip)
                                    .addGap(69, 69, 69)
                                    .addComponent(cajaip, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hdmi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(combohdmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(usb)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(combousb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equipo, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaresolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ram, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajadd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajapulgadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lector, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combolector, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ip, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cajaip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hdmi)
                    .addComponent(combohdmi, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combousb, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(impresora)
                            .addComponent(cajaimpresora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marca)
                    .addComponent(cajamarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeloddd)
                    .addComponent(cajamodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serie)
                            .addComponent(cajaserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(explicaion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipoActionPerformed
        // TODO add your handling code here:
        int bloqueo = equipo.getSelectedIndex();
        if(bloqueo == 1){

            impresora.setVisible(true);
            cajaimpresora.setVisible(true);
            ip.setVisible(false);
            cajaip.setVisible(false);
            resolucion.setVisible(false);
            cajaresolucion.setVisible(false);
            ram.setVisible(false);
            cajaram.setVisible(false);
            dd.setVisible(false);
            cajadd.setVisible(false);
            pulgadas.setVisible(false);
            cajapulgadas.setVisible(false);
            lector.setVisible(false);
            combolector.setVisible(false);
            hdmi.setVisible(false);
            combohdmi.setVisible(false);
            usb.setVisible(false);
            combousb.setVisible(false);
        }
        if(bloqueo == 2){

            resolucion.setVisible(true);
            cajaresolucion.setVisible(true);
            ram.setVisible(true);
            cajaram.setVisible(true);
            dd.setVisible(true);
            cajadd.setVisible(true);
            pulgadas.setVisible(true);
            cajapulgadas.setVisible(true);
            lector.setVisible(true);
            combolector.setVisible(true);
            hdmi.setVisible(true);
            combohdmi.setVisible(true);
            usb.setVisible(true);
            combousb.setVisible(true);
            ip.setVisible(false);
            cajaip.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);

        }
        if(bloqueo == 3){

            resolucion.setVisible(true);
            cajaresolucion.setVisible(true);
            ram.setVisible(true);
            cajaram.setVisible(true);
            dd.setVisible(true);
            cajadd.setVisible(true);
            pulgadas.setVisible(true);
            cajapulgadas.setVisible(true);
            lector.setVisible(true);
            combolector.setVisible(true);
            hdmi.setVisible(true);
            combohdmi.setVisible(true);
            usb.setVisible(true);
            combousb.setVisible(true);
            ip.setVisible(false);
            cajaip.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
        }
        if(bloqueo==4){
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
            ip.setVisible(true);
            cajaip.setVisible(true);
            resolucion.setVisible(false);
            cajaresolucion.setVisible(false);
            ram.setVisible(false);
            cajaram.setVisible(false);
            dd.setVisible(false);
            cajadd.setVisible(false);
            pulgadas.setVisible(false);
            cajapulgadas.setVisible(false);
            lector.setVisible(false);
            combolector.setVisible(false);
            hdmi.setVisible(false);
            combohdmi.setVisible(false);
            usb.setVisible(false);
            combousb.setVisible(false);

        }
        if(bloqueo == 5){

            resolucion.setVisible(true);
            cajaresolucion.setVisible(true);
            hdmi.setVisible(true);
            combohdmi.setVisible(true);
            usb.setVisible(true);
            combousb.setVisible(true);
            ram.setVisible(false);
            cajaram.setVisible(false);
            dd.setVisible(false);
            cajadd.setVisible(false);
            pulgadas.setVisible(false);
            cajapulgadas.setVisible(false);
            lector.setVisible(false);
            combolector.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
            ip.setVisible(false);
            cajaip.setVisible(false);

        }
        if(bloqueo == 6){

            resolucion.setVisible(true);
            cajaresolucion.setVisible(true);
            hdmi.setVisible(true);
            combohdmi.setVisible(true);
            usb.setVisible(true);
            combousb.setVisible(true);
            ram.setVisible(false);
            cajaram.setVisible(false);
            dd.setVisible(false);
            cajadd.setVisible(false);
            pulgadas.setVisible(false);
            cajapulgadas.setVisible(false);
            lector.setVisible(false);
            combolector.setVisible(false);
            impresora.setVisible(false);
            cajaimpresora.setVisible(false);
            ip.setVisible(false);
            cajaip.setVisible(false);

        }
    }//GEN-LAST:event_equipoActionPerformed

    private void cajaresolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaresolucionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaresolucionActionPerformed

    private void cajaramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaramActionPerformed

    private void cajaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaddActionPerformed

    private void cajapulgadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajapulgadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajapulgadasActionPerformed

    private void combolectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combolectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combolectorActionPerformed

    private void cajaipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaipActionPerformed

    private void cajaimpresoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaimpresoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaimpresoraActionPerformed

    private void cajamarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajamarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajamarcaActionPerformed

    private void cajamodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajamodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajamodeloActionPerformed

    private void cajaserieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaserieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaserieActionPerformed

    private void explicaionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explicaionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_explicaionActionPerformed

    private void combohdmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combohdmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combohdmiActionPerformed

    private void combousbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combousbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combousbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresosArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresosArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresosArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresosArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresosArticulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cajadd;
    private javax.swing.JTextField cajaimpresora;
    private javax.swing.JTextField cajaip;
    private javax.swing.JTextField cajamarca;
    private javax.swing.JTextField cajamodelo;
    private javax.swing.JTextField cajapulgadas;
    private javax.swing.JTextField cajaram;
    private javax.swing.JTextField cajaresolucion;
    private javax.swing.JTextField cajaserie;
    private javax.swing.JComboBox combohdmi;
    private javax.swing.JComboBox combolector;
    private javax.swing.JComboBox combousb;
    private javax.swing.JLabel dd;
    private javax.swing.JComboBox equipo;
    private javax.swing.JTextField explicaion;
    private javax.swing.JLabel hdmi;
    private javax.swing.JLabel impresora;
    private javax.swing.JLabel ip;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lector;
    private javax.swing.JLabel marca;
    private javax.swing.JLabel modeloddd;
    private javax.swing.JLabel pulgadas;
    private javax.swing.JLabel ram;
    private javax.swing.JLabel resolucion;
    private javax.swing.JLabel serie;
    private javax.swing.JLabel usb;
    // End of variables declaration//GEN-END:variables
}
